### ISSUE TITLE
Fabric Please?

### ISSUE THREAD

**Issue by PSGitHubUser1** [Gregory-AM/ReStructure-Plugin#1]
This is a way to /locate structures 
https://youtu.be/xI-NEQmE4fs?si=Gjq9Y5qZYxcGiPZc

But you automated this process for Data Pack, so can you do this for Fabric and Forge 1.20.1? btw, I like Fabric (my preferance) because its lightweight.

**Comment by Gregory-AM** [comment]
Hey, @PSGitHubUser1!
Yes, I'll see what I can do for Fabric.

**Comment by PSGitHubUser1** [comment]
what?

**Comment by Gregory-AM** [comment]
Since Fabric is another Generator in MCreator.
Adding the same functionality is a bit different.
I'll see what I can do to get it working with the 1.20.1 Fabric Generator.

**Comment by PSGitHubUser1** [comment]
Thanks ;)

**Comment by Gregory-AM** [comment]
Support for Fabric Generator has been added, @PSGitHubUser1 .
[**[Re]**Structure](https://mcreator.net/plugin/100952/restructure)

**Comment by PSGitHubUser1** [comment]
![image](https://github.com/Gregory-AM/ReStructure-Plugin/assets/90406016/ba7c27c6-58e1-44ea-8372-1f78759b4c10)
If this is the case then it is good to Reopen this Issue...

**Comment by Gregory-AM** [comment]
> ![image](https://user-images.githubusercontent.com/90406016/274853431-ba7c27c6-58e1-44ea-8372-1f78759b4c10.png) If this is the case then it is good to Reopen this Issue...

Reopening the issue won't be necessary. Since it's something already known about and will be added back shortly after it's release.

v1.0.0 was built just like the original, with forge in mind. Since the deadline is Monday, forge will be the only available version [Re]Structure will work with for about 48 hours. Then Fabric, then 1.18.2.😁

**Comment by Gregory-AM** [comment]
@PSGitHubUser1, v1.0.0 will be supporting fabric.
I'm about to update my announcement.

I was able to push through the night and update it to work properly before Monday.
